### ISSUE TITLE
Silence recommendation to upgrade my workspace when a new template has been uploaded

### ISSUE THREAD

**Issue by amanibhavam** [coder/vscode-coder#114]
Can the extension silence the pop-up recommendations to upgprade my workspace that appear whenever a new template is uploaded?  As a template author, I don't want my users to get the notification when most of my updates are not essential.

**Comment by matifali** [comment]
@stirby would be able to provide an opinion here.

**Comment by stirby** [comment]
In Q4 this year, we'll change how we manage VSCode notifications and give users more control.

In the meantime, we advise only pushing updates outside of working hours and enforcing nightly updates with [Autostop Requirement](https://coder.com/docs/workspaces#autostop-requirement-enterprise). Or use a different staging template for testing and development. 

Otherwise this isn't something we plan to implement as a standalone item.
