### ISSUE TITLE
Display quota errors in VS Code extension

### ISSUE THREAD

**Issue by bpmct** [coder/vscode-coder#117]
This is what I see instead

![Screenshot 2023-07-21 at 12 22 11 PM](https://github.com/coder/vscode-coder/assets/22407953/81052ec7-0ba3-416a-8d0a-9caaec6f4eeb)

The quotas error:

![Screenshot 2023-07-21 at 12 22 27 PM](https://github.com/coder/vscode-coder/assets/22407953/b973960c-a935-4457-8ede-e11a367c3401)

**Comment by matifali** [comment]
@code-asher we already stream build logs from terarform to VSCode. I wonder how the Commit quota information is being displayed. Do we need changes in coder/coder to support this?

**Comment by code-asher** [comment]
We recently made a change to use the cli to start the workspace and display the stderr if it fails, so it is possible this will actually show up in the error now.

I think it could also make sense to have the ability to review the build log on error.  Right now we immediately close it on error so it is not possible to review it to see what might have gone wrong.

**Comment by matifali** [comment]
So we can instead parse the error log for any errors and show them via extension. We can do it along with coder/coder#15447

**Comment by matifali** [comment]
This is nice that we have it already. Can we make this error more notable by highlighting the Quota issue instead of "Failed to Open Workspace"?

**Comment by code-asher** [comment]
Part of me prefers the way it is now, because the action it tried to do was open the workspace, and the message then describes why that action failed.

But, if we feel this is obscuring the error and moving the stderr above is better, then that seems reasonable enough to me.  Do note though that stderr could be anything though, it could be about quotas or anything else, and a dynamic title also feels a little weird to me.

**Comment by code-asher** [comment]
It also seems unfortunate that we display the "run coder --help" part when the user has no way to actually do that.  I wonder if the cli needs a kind of "inactive" mode that displays different error messages when running as part of a plugin (and maybe it would output in json instead as well, so we could parse and use the errors however we want, instead of dealing with arbitrary text).

**Comment by matifali** [comment]
Yeah. IMO we should only show `coder<subcommand> --help` if the command or argument is not valid and otherwise just print the error message.
