### ISSUE TITLE
Negative space in the coder sidebar

### ISSUE THREAD

**Issue by deansheather** [coder/vscode-coder#4]
There's lots of negative space in the sidebar added by the extension. Could we perhaps list workspaces that match `owner:me`, refreshing every minute or something (with a refresh button to refresh now)? This would help avoid having to click "Open Workspace" if users are only using their own workspaces.

![image](https://user-images.githubusercontent.com/11241812/210479210-b2ae4d06-0c43-48f0-8589-6f1ecf01fead.png)

**Comment by jsjoeio** [comment]
I'll start working on this tomorrow!

**Comment by jsjoeio** [comment]
## Notes

I started digging into this. I thought, "Ah this will be easy!!" but it turns out it's a little bit more complex. Currently, we use what's called "Welcome content".

This API allows us to contribute a `viewWelcome` and specify very basic `contents` as a string with support for links/buttons. We currently do this as so:

```json
    "viewsWelcome": [
      {
        "view": "coderRemote",
        "contents": "You're logged in! \n[Open Workspace](command:coder.open)",
        "when": "coder.authenticated && coder.loaded"
      }
    ],
```

If we want to display more complex data - aka a list of workspaces - we'll need to [contribute a view to this View Container](https://code.visualstudio.com/api/extension-guides/tree-view#contributing-views-to-view-containers).

I'm currently playing around with the [`tree-view-sample`](https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample) to figure out how to do that. 

So that's the first step: if not logged in, display "login coder" as a `viewWelcome`, otherwise, display custom tree view.
