### ISSUE TITLE
Respect proxies

### ISSUE THREAD

**Issue by bpmct** [coder/vscode-coder#78]
I thought there was an issue for this, but it seems like there is not? How can the VS Code extension work with `HTTP_PROXY`, etc

**Comment by ericpaulsen** [comment]
@bpmct @rodrimaia i'm running Coder Remote `v0.1.18`, with the `http_proxy` set to `http://google.com`.

i am correctly getting self-signed certificate errors when this env var is set, and successful connections when unset. the extension appears to respect the configured proxy.

<img width="819" alt="Screenshot 2023-05-04 at 9 47 12 PM" src="https://user-images.githubusercontent.com/9683576/236362574-f159540e-3a30-413b-b201-406f4e0caf74.png">

**Comment by rodrimaia** [comment]
@ericpaulsen thank you for your comment. Your results match what I have been testing too. 

I conducted local tests using the `tinyproxy` proxy to confirm there are no errors with the extension interaction. 

1. The coder extension adheres to the same proxy settings used by VSCode itself. Users can customize this behavior through the VSCode user preferences, where the default option is set to "override.": 
![image](https://user-images.githubusercontent.com/2081077/236567233-3e32e9cf-bb31-41bf-9fd5-f6d4e2c4fb06.png)

2. There are three methods to configure the VSCode proxy:
   a. Launching VSCode with the `http_proxy` environment variable.
   b. Modifying the proxy settings within the user preferences section.
   c. Allowing VSCode to automatically inherit proxy settings from the operating system.

In all cases, the coder extension effectively utilized the same proxy as VSCode.

I could not figure out why some users faced those network/connectivity errors in the past. 

@bpmct do you see anything else that can be run/tested to improve this issue clarification?

**Comment by tiaden1** [comment]
I'm having the same issue. Our root certificate is a corporate root certificate that is installed in every user Windows 10 environment. Thus it's trusted by Google chrome but when used inside vscode for coder CLI auth, I get the error below.  I tried everything. From setting the proxy to **override** to the use of the **NODE_EXTRA_CA_CERTS** environment variable. 
The only thing that works is setting the environment variable **NODE_TLS_REJECT_UNAUTHORIZED** to 0 in order to bypass certificate verification. However as we all know, this is not secure.
<img width="1667" alt="Screenshot 2023-05-29 at 6 48 14 PM" src="https://github.com/coder/vscode-coder/assets/93949358/4f98f650-b7ca-46b7-aa95-a9a09e17766f">
